// This file is manually generated by DataManager.cs, don't modify directly
// Entries are generated from found Schema.Audio.AudioDataSchema scriptable objects in the Data folder

public static partial class AudioTypeUtility
{
	public static Schema.Audio.AudioDataSchema GetSchema(this Schema.AudioType enumValue)
	{
		return Schema.DataManager.Instance.AudioClips[(int)enumValue - 1];
	}
}

namespace Schema
{
	public enum AudioType
	{
		None,
		_Count
	}

}